acme_test_homepage:
    path:     /hello/{name}
    defaults: { _controller: AcmeTestBundle:Default:index }

hello:
    path:     /whatsup/
    defaults: { _controller: AcmeTestBundle:Default:hello }

blog:
  path: /blog/{slug}
  defaults : {_controller: AcmeTestBundle:Default:show}